"""Type stubs for slack_sdk."""

from typing import Any

class WebClient:
    def __init__(self, token: str, **kwargs: Any) -> None: ...

class AsyncWebClient:
    def __init__(self, token: str, **kwargs: Any) -> None: ...
    async def chat_postMessage(self, **kwargs: Any) -> AsyncSlackResponse: ...
    async def views_open(self, **kwargs: Any) -> AsyncSlackResponse: ...
    async def files_remote_add(self, **kwargs: Any) -> AsyncSlackResponse: ...
    async def users_list(self, **kwargs: Any) -> AsyncSlackResponse: ...

class AsyncSlackResponse:
    data: dict[str, Any]
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...
